import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import ElementPlus from "element-plus";
import "element-plus/lib/theme-chalk/index.css";
import store from "./store";
import { axionInit } from '@/js/axios.config';
const app = createApp(App);
app.use(store).use(router).use(ElementPlus).mount("#app");
axionInit();
